title = "Ian H. Chamberlain"
description = "Ian's personal website"

base_url = "https://ian-h-chamberlain.github.io"
default_language = "en"
theme = "serene"

build_search_index = false
generate_feed = false
compile_sass = true
minify_html = true

[markdown]
render_emoji = true
smart_punctuation = true
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["themes/serene/highlight_themes"]
# Note: need to delete these generated files for changes to take effect:
highlight_themes_css = [
    { theme = "monokai", filename = "hl-dark.css" },
    { theme = "base16-atelierdune-light", filename = "hl-light.css" },
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
name = "Ian H. Chamberlain"
id = "ian-h-chamberlain"
# TODO: see if we can put newlines in here somehow. Also not sure if I like the brackets
# Also may want to hold off on pronouns at first publish?
bio = """(they/them)

[ software engineer | game developer | ??? ]"""

avatar = "images/avatar.png"
links = [
    { name = "GitHub", icon = "github", url = "https://github.com/ian-h-chamberlain" },
    { name = "itch", icon = "itchio-logo-textless", url = "https://ian-h-chamberlain.itch.io" },
    { name = "Email", icon = "email", url = "mailto:contact@ian-h-chamberlain.com" },
]

homepage_layout = "about" # "about" | "list"

sections = [
    # TODO: not 100% sure on the name "experience". "work"? "career"? "background"? "resume"?
    { name = "experience", path = "/experience", is_external = false },
    { name = "projects", path = "/projects", is_external = false },
    { name = "open source", path = "/open-source", is_external = false },
]

nav_separator = '|>'
nav_wrapper_left = "["
nav_wrapper_right = "]"
nav_wrapper_separator = "|"

display_id = true       # Whether to display your id on homepage
blog_categorized = true # Whether to categorize blog posts
blur_effect = true      # Whether to turn on blur effect on navigation bar
back_to_top = true      # Whether to show back-to-top button on post pages

toc = false              # Whether to show Table-Of-Contents by default
copy = true              # Whether to add a copy button on code blocks by default
comment = false          # Whether to show giscus comment section by default, see https://giscus.app for more info
display_tags = true      # Whether to display tags on post pages by default
truncate_summary = false # Whether to truncate the summary of a post by default

outdate_alert = false                                          # Whether to show outdate alert by default
outdate_alert_days = 120                                       # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

# TODO: include link to a licenses page for fonts, theme etc?
footer_copyright = "© 2023 Ian Chamberlain"
footer_credits = true                       # Whether to show "powered by zola and serene" in footer

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"
