name: Deploy Zola on GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Build and check only
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          CHECK_LINKS: true
          CHECK_FLAGS: --drafts

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          CHECK_LINKS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
